// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.0
// 	protoc        v3.21.12
// source: embedding.proto

package proto

import (
	_ "google.golang.org/grpc"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckLoopRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TenantId string `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Prompt   string `protobuf:"bytes,2,opt,name=prompt,proto3" json:"prompt,omitempty"`
}

func (x *CheckLoopRequest) Reset() {
	*x = CheckLoopRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_embedding_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckLoopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckLoopRequest) ProtoMessage() {}

func (x *CheckLoopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_embedding_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckLoopRequest.ProtoReflect.Descriptor instead.
func (*CheckLoopRequest) Descriptor() ([]byte, []int) {
	return file_embedding_proto_rawDescGZIP(), []int{0}
}

func (x *CheckLoopRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CheckLoopRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

type CheckLoopResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LoopDetected  bool    `protobuf:"varint,1,opt,name=loop_detected,json=loopDetected,proto3" json:"loop_detected,omitempty"`
	MaxSimilarity float64 `protobuf:"fixed64,2,opt,name=max_similarity,json=maxSimilarity,proto3" json:"max_similarity,omitempty"`
	SimilarPrompt string  `protobuf:"bytes,3,opt,name=similar_prompt,json=similarPrompt,proto3" json:"similar_prompt,omitempty"`
}

func (x *CheckLoopResponse) Reset() {
	*x = CheckLoopResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_embedding_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckLoopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckLoopResponse) ProtoMessage() {}

func (x *CheckLoopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_embedding_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckLoopResponse.ProtoReflect.Descriptor instead.
func (*CheckLoopResponse) Descriptor() ([]byte, []int) {
	return file_embedding_proto_rawDescGZIP(), []int{1}
}

func (x *CheckLoopResponse) GetLoopDetected() bool {
	if x != nil {
		return x.LoopDetected
	}
	return false
}

func (x *CheckLoopResponse) GetMaxSimilarity() float64 {
	if x != nil {
		return x.MaxSimilarity
	}
	return 0
}

func (x *CheckLoopResponse) GetSimilarPrompt() string {
	if x != nil {
		return x.SimilarPrompt
	}
	return ""
}

var File_embedding_proto protoreflect.FileDescriptor

var file_embedding_proto_rawDesc = []byte{
	0x0a, 0x10, 0x65, 0x6d, 0x62, 0x65, 0x64, 0x64, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x09, 0x65, 0x6d, 0x62, 0x65, 0x64, 0x64, 0x69, 0x6e, 0x67, 0x22, 0x3a,
	0x0a, 0x11, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x4c, 0x6f, 0x6f, 0x70, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74,
	0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x22, 0x73, 0x0a, 0x12,
	0x43, 0x68, 0x65, 0x63, 0x6b, 0x4c, 0x6f, 0x6f, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x22, 0x0a, 0x0d, 0x6c, 0x6f, 0x6f, 0x70, 0x5f, 0x64, 0x65, 0x74, 0x65,
	0x63, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x6c, 0x6f, 0x6f,
	0x70, 0x44, 0x65, 0x74, 0x65, 0x63, 0x74, 0x65, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x6d, 0x61,
	0x78, 0x5f, 0x73, 0x69, 0x6d, 0x69, 0x6c, 0x61, 0x72, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x0d, 0x6d, 0x61, 0x78, 0x53, 0x69, 0x6d, 0x69, 0x6c, 0x61, 0x72,
	0x69, 0x74, 0x79, 0x12, 0x25, 0x0a, 0x0e, 0x73, 0x69, 0x6d, 0x69, 0x6c, 0x61, 0x72, 0x5f,
	0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x73,
	0x69, 0x6d, 0x69, 0x6c, 0x61, 0x72, 0x50, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x32, 0x51, 0x0a,
	0x10, 0x45, 0x6d, 0x62, 0x65, 0x64, 0x64, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x3d, 0x0a, 0x09, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x4c, 0x6f, 0x6f, 0x70,
	0x12, 0x1c, 0x2e, 0x65, 0x6d, 0x62, 0x65, 0x64, 0x64, 0x69, 0x6e, 0x67, 0x2e, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x4c, 0x6f, 0x6f, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1d, 0x2e, 0x65, 0x6d, 0x62, 0x65, 0x64, 0x64, 0x69, 0x6e, 0x67, 0x2e, 0x43, 0x68, 0x65,
	0x63, 0x6b, 0x4c, 0x6f, 0x6f, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x42, 0x17, 0x5a, 0x15, 0x65, 0x6d, 0x62, 0x65, 0x64, 0x64, 0x69, 0x6e, 0x67, 0x2d,
	0x73, 0x69, 0x64, 0x65, 0x63, 0x61, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_embedding_proto_rawDescOnce sync.Once
	file_embedding_proto_rawDescData = file_embedding_proto_rawDesc
)

func file_embedding_proto_rawDescGZIP() []byte {
	file_embedding_proto_rawDescOnce.Do(func() {
		file_embedding_proto_rawDescData = protoimpl.X.CompressGZIP(file_embedding_proto_rawDescData)
	})
	return file_embedding_proto_rawDescData
}

var file_embedding_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_embedding_proto_goTypes = []interface{}{
	(*CheckLoopRequest)(nil),  // 0: embedding.CheckLoopRequest
	(*CheckLoopResponse)(nil), // 1: embedding.CheckLoopResponse
}
var file_embedding_proto_depIdxs = []int32{
	0, // 0: embedding.EmbeddingService.CheckLoop:input_type -> embedding.CheckLoopRequest
	1, // 1: embedding.EmbeddingService.CheckLoop:output_type -> embedding.CheckLoopResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_embedding_proto_init() }
func file_embedding_proto_init() {
	if File_embedding_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_embedding_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckLoopRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_embedding_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckLoopResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_embedding_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_embedding_proto_goTypes,
		DependencyIndexes: file_embedding_proto_depIdxs,
		MessageInfos:      file_embedding_proto_msgTypes,
	}.Build()
	File_embedding_proto = out.File
	file_embedding_proto_rawDesc = nil
	file_embedding_proto_goTypes = nil
	file_embedding_proto_depIdxs = nil
}
