// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.26.1
// source: embedding.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckLoopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Prompt        string                 `protobuf:"bytes,2,opt,name=prompt,proto3" json:"prompt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckLoopRequest) Reset() {
	*x = CheckLoopRequest{}
	mi := &file_embedding_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckLoopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckLoopRequest) ProtoMessage() {}

func (x *CheckLoopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_embedding_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckLoopRequest.ProtoReflect.Descriptor instead.
func (*CheckLoopRequest) Descriptor() ([]byte, []int) {
	return file_embedding_proto_rawDescGZIP(), []int{0}
}

func (x *CheckLoopRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CheckLoopRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

type CheckLoopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LoopDetected  bool                   `protobuf:"varint,1,opt,name=loop_detected,json=loopDetected,proto3" json:"loop_detected,omitempty"`
	MaxSimilarity float64                `protobuf:"fixed64,2,opt,name=max_similarity,json=maxSimilarity,proto3" json:"max_similarity,omitempty"`
	SimilarPrompt string                 `protobuf:"bytes,3,opt,name=similar_prompt,json=similarPrompt,proto3" json:"similar_prompt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckLoopResponse) Reset() {
	*x = CheckLoopResponse{}
	mi := &file_embedding_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckLoopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckLoopResponse) ProtoMessage() {}

func (x *CheckLoopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_embedding_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckLoopResponse.ProtoReflect.Descriptor instead.
func (*CheckLoopResponse) Descriptor() ([]byte, []int) {
	return file_embedding_proto_rawDescGZIP(), []int{1}
}

func (x *CheckLoopResponse) GetLoopDetected() bool {
	if x != nil {
		return x.LoopDetected
	}
	return false
}

func (x *CheckLoopResponse) GetMaxSimilarity() float64 {
	if x != nil {
		return x.MaxSimilarity
	}
	return 0
}

func (x *CheckLoopResponse) GetSimilarPrompt() string {
	if x != nil {
		return x.SimilarPrompt
	}
	return ""
}

var File_embedding_proto protoreflect.FileDescriptor

const file_embedding_proto_rawDesc = "" +
	"\n" +
	"\x0fembedding.proto\x12\tembedding\"G\n" +
	"\x10CheckLoopRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x16\n" +
	"\x06prompt\x18\x02 \x01(\tR\x06prompt\"\x86\x01\n" +
	"\x11CheckLoopResponse\x12#\n" +
	"\rloop_detected\x18\x01 \x01(\bR\floopDetected\x12%\n" +
	"\x0emax_similarity\x18\x02 \x01(\x01R\rmaxSimilarity\x12%\n" +
	"\x0esimilar_prompt\x18\x03 \x01(\tR\rsimilarPrompt2Z\n" +
	"\x10EmbeddingService\x12F\n" +
	"\tCheckLoop\x12\x1b.embedding.CheckLoopRequest\x1a\x1c.embedding.CheckLoopResponseB\x1fZ\x1dembedding-sidecar/proto;protob\x06proto3"

var (
	file_embedding_proto_rawDescOnce sync.Once
	file_embedding_proto_rawDescData []byte
)

func file_embedding_proto_rawDescGZIP() []byte {
	file_embedding_proto_rawDescOnce.Do(func() {
		file_embedding_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_embedding_proto_rawDesc), len(file_embedding_proto_rawDesc)))
	})
	return file_embedding_proto_rawDescData
}

var file_embedding_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_embedding_proto_goTypes = []any{
	(*CheckLoopRequest)(nil),  // 0: embedding.CheckLoopRequest
	(*CheckLoopResponse)(nil), // 1: embedding.CheckLoopResponse
}
var file_embedding_proto_depIdxs = []int32{
	0, // 0: embedding.EmbeddingService.CheckLoop:input_type -> embedding.CheckLoopRequest
	1, // 1: embedding.EmbeddingService.CheckLoop:output_type -> embedding.CheckLoopResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_embedding_proto_init() }
func file_embedding_proto_init() {
	if File_embedding_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_embedding_proto_rawDesc), len(file_embedding_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_embedding_proto_goTypes,
		DependencyIndexes: file_embedding_proto_depIdxs,
		MessageInfos:      file_embedding_proto_msgTypes,
	}.Build()
	File_embedding_proto = out.File
	file_embedding_proto_goTypes = nil
	file_embedding_proto_depIdxs = nil
}
